{{- if and .Values.activeMQ.enabled }}
apiVersion: v1
data:
  ca_certs: {{ .Values.activeMQ.ca_certs | b64enc | quote}}
  client_cert: {{ .Values.activeMQ.client_cert | b64enc | quote}}
  client_key: {{ .Values.activeMQ.client_key | b64enc | quote}}
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-msg-certs
{{- end }}
