{{- $fullName := include "..fullname" . -}}
{{- if .Values.openshift.enabled }}
{{- range $host := .Values.openshift.hosts }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $host | replace "." "-" | trunc 63 | trimSuffix "-" }}
spec:
  host: {{ $host }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
{{ include "chart.helmRouteFix" $ }}
{{- end }}
{{- end }}
