apiVersion: v1
data:
  host: {{ .Values.smtp.endpoint.host | b64enc | quote }}
  port: {{ .Values.smtp.endpoint.port | toString | b64enc | quote }}
  tls: {{ .Values.smtp.endpoint.enableTls | toString | b64enc | quote}}
{{- if .Values.smtp.endpoint.user }}
  user: {{ .Values.smtp.endpoint.user | b64enc | quote }}
{{- end }}
{{- if .Values.smtp.endpoint.password }}
  password: {{ .Values.smtp.endpoint.password | toString | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-smtp
