apiVersion: v1
data:
  host: {{ .Values.smtp.endpoint.host | quote | b64enc }}
  port: {{ .Values.smtp.endpoint.port | b64enc }}
  tls: {{ .Values.smtp.endpoint.enableTls | b64enc }}
{{- if .Values.smtp.endpoint.user }}
  user: {{ .Values.smtp.endpoint.user | quote | b64enc }}
{{- end }}
{{- if .Values.smtp.endpoint.password }}
  password: {{ .Values.smtp.endpoint.password | quote | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-smtp
