name: Flake8

on:
  push:
    paths:
    - "app/**/*.py"
  pull_request:
    paths:
    - "app/**/*.py"

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout notify-service
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Flake8 action
      uses: suo/flake8-github-action@v1
